public with sharing class csaHmdaExtractConstants {
    public static final String PROPERTY_INSTALLEDKEY = 'nCino_HMDA_Extract';
    public static final String PROPERTY_INSTALLEDVALUE = 'true';
    public static final String PROPERTY_CUSTOMFIELDKEY = 'HMDA_Extract_Custom_Field';
    public static final String PROPERTY_CUSTOMERFIELDVALUE = 'LLC_BI__HMDA_Date_Action_Taken__c';
    public static final String PROPERTY_EMAILKEY = 'HMDA_Extract_Email_Generation';
    public static final String PROPERTY_EMAILVALUE = UserInfo.getUserEmail();
    public static final String PROERPTY_CATEGORY = 'CSA HMDA Extract';
    public static final String ROUTE_APPNAME = 'csa-hmda-extract-generator';
    public static final String ROUTE_NAME = 'nCino HMDA Extract Generator';
    public static final String STARTDATE = 'startDate';
    public static final String ENDDATE = 'endDate';
}